### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [adamviola/EntityOutliner#17]
Hello, I've tried to open the settings and got this crash log here:

Unhandled game exception
java.lang.NoSuchMethodError: 'void net.minecraft.class_309.method_1462(boolean)'
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at net.entityoutliner.ui.EntitySelector.removed(EntitySelector.java:197)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:1024)
	at net.minecraft.client.MinecraftClient.reset(MinecraftClient:2193)
	at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient:2164)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.cleanupBeforeMinecraft(InGameCatcher.java:54)
	at net.minecraft.client.MinecraftClient.handler$gpk000$beforeCleanUpAfterCrash(MinecraftClient:34060)
	at net.minecraft.client.MinecraftClient.cleanUpAfterCrash(MinecraftClient)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:801)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Glowbomb12** [comment]
Same issue. Opening the config either through Mod Menu or the keybind produces a crash. 

https://pastebin.com/q6eznpi9

**Comment by adamviola** [comment]
Thanks for the issue! Will try to update within the next week or two.

**Comment by venaminecraft** [comment]
Thanks, don't rush it please ☺️

**Comment by adamviola** [comment]
Updated to 1.19.3! Let me know if you find any bugs :)

**Comment by venaminecraft** [comment]
Thank you 🥳
